apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kove-k8s-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kove-k8s-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kove-k8s-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kove-k8s-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: quay.io/ecosystem-appeng/kove-k8s-device-plugin
        imagePullPolicy: Always
        name: kove-k8s-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 10Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
#        - name: dev
#          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
#      - name: dev
#        hostPath:
#          path: /dev
  updateStrategy:
    type: RollingUpdate
